---
version: 12.2.0-1
slug: sambaplus
name: Samba+
description: Expose folders with SMB/CIFS
url: https://github.com/vuvova/hass-addons/tree/master/samba
codenotary: vuvova@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  workgroup: WORKGROUP
  compatibility_mode: false
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
  shares:
    - share: addons
    - share: addon_configs
    - share: backup
    - share: config
    - share: media
    - share: share
    - share: ssl
  users:
    - username: homeassistant
      password: qwerty
schema:
  workgroup: str
  compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
  shares:
    - share: str
      users:
        - str?
      ro_users:
        - str?
  users:
    - username: str
      password: str
startup: services
